### ISSUE TITLE
No ticket matches when new tickets were added

### ISSUE THREAD

**Issue by pawKer** [ahobsonsayers/twitchets#5]
Hi! 👋 I was trying to set this up but unfortunately I have not been receiving any notifications from it while I was still getting the app notifications when new tickets were added :(

This is my config:
```
apiKey: <api-key> 

country: GB

notification:
  ntfy:
    url: ntfy.sh
    topic: <topic>
  telegram:
    token: <token>
    chatId: <chat-id>

global:
  regions:
    - GBNW 
    - GBNE
    - GBNO

  eventSimilarity: 0.85

tickets:
  - event: Deftones
  - event: Fontaines D.C.
```

And these are the logs from the Docker container:
```
2025/06/19 13:25:02 INFO Monitoring: Deftones, Fontaines D.C.
```

Have I misconfigured something or maybe they've changed something on their side?
